// Generated by https://quicktype.io

export interface FaceDetect {
    faceId: string;
    faceRectangle: FaceRectangle;
}

export interface FaceRectangle {
    top: number;
    left: number;
    width: number;
    height: number;
}
