// Generated by https://quicktype.io

export interface Student {
    id: string;
    group: string;
    faceId?: string;
    phoneNumber: number;
    matricula: string;
    img: string;
    expiresIn?: number;
    name: string;
    career: string;
    quarter: number;
}
